# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33d5c3aa00cee343df981474c3239454b6a771a82e52ac99a2bf0b41553a499790eb5799fb4c6119a6c969f252426d97dd4fe1059c212224b30d1b91659b2073

test:
  secret_key_base: 37a02aa1954039c1e07038174ece906aa6a6fbc094765c60d3f3bfa889161248e94672a272e7ee8c7c247826d35bd430d59dfd922056e7dfbae93cb1af62acc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
